#!/bin/bash
#SBATCH -N 1
#SBATCH -C knl
#SBATCH -q debug
#SBATCH -J cs267
#SBATCH -t 00:30:00

#run the application:
#srun -n 1 -c 1 --cpu_bind=cores ./serial -f ../../sample-graphs/graph2.csv -n 1000 -s 31 -o openmp.out

#srun -n 1 -c 1 --cpu_bind=cores ./serial -f ../../sample-graphs/big-graphs/amazonDigitalMusic_core5_edges2.csv -n 1000 -s 1
#srun -n 1 -c 1 --cpu_bind=cores ./serial -f ../../sample-graphs/big-graphs/amazonMusicalInstruments_core5_edges2.csv -n 1000 -s 1
srun -n 1 -c 1 --cpu_bind=cores ./serial -f ../../sample-graphs/big-graphs/amazonVideo_core5_edges2.csv -n 1000 -s 1
#srun -n 1 -c 1 --cpu_bind=cores ./serial -f ../../sample-graphs/big-graphs/all_wiki_edges.csv -n 1000 -s 1

#srun -n 1 -c 1 --cpu_bind=cores ./serial -f ../../sample-graphs/big-graphs/Amazon_Android_edges2.csv -n 1000 -s 1
#srun -n 1 -c 1 --cpu_bind=cores ./serial -f ../../sample-graphs/big-graphs/Amazon_Games_edges2.csv -n 1000 -s 1
#srun -n 1 -c 1 --cpu_bind=cores ./serial -f ../../sample-graphs/big-graphs/Amazon_Baby_edges2.csv -n 1000 -s 1
#srun -n 1 -c 1 --cpu_bind=cores ./serial -f ../../sample-graphs/big-graphs/Amazon_Automotive_edges2.csv -n 1000 -s 1

