#!/bin/bash
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -p GPU-shared
#SBATCH -t 00:30:00
#SBATCH --gres=gpu:1

input_csv=${1}
output_csv=${2}

./graphBplusOptimization ~/dataset/${input_csv} 1000 ${output_csv}