#!/bin/bash
#SBATCH -N 1
#SBATCH -C knl
#SBATCH -q debug
#SBATCH -J cs267
#SBATCH -t 00:30:00

#OpenMP settings:
export OMP_NUM_THREADS=68
export OMP_PLACES=cores
export OMP_PROC_BIND=spread

#run the application:
srun -n 1 -c 68 --cpu_bind=cores ./openmp -f ../../../sample-graphs/graph2.csv -n 1000 -s 1 -o openmp.out
#srun -n 1 -c 68 --cpu_bind=cores ./openmp -f ../../../sample-graphs/big-graphs/amazonDigitalMusic_core5_edges2.csv -n 1000
